export enum AutoDevCommand {
	QuickFix = "autodev.quickFix",
	SendToTerminal = "autodev.sendToTerminal",
	DebugTerminal = "autodev.debugTerminal",
	AutoComment = "autodev.autoComment",
	AutoTest = "autodev.autoTest",
	Explain = "autodev.explain",
	FixThis = "autodev.fixThis",
	MenuAutoComment = "autodev.menu.autoComment",
	TerminalExplainContextMenu = "autodev.terminal.explainTerminalSelectionContextMenu",
	ActionQuickAction = "autodev.action.quickAction",
	SystemAction = "autodev.systemAction",
	GenerateCommitMessage = "autodev.git.generateCommitMessage",
	GenApiData = "autodev.genApiData",
}
